---
title: "Group 8 Project"
subtitle: "PIXE analysis on Maya blue in Prehispanic and colonial mural paintings"
author: "Awet, Connor, Lachlan, Pablo,"
format: html
editor: visual
---

```{r}
#| include: false
library("readxl")
Table1 <- read_excel("../Data/Table1_clean.xlsx")
Table1
Table1_raw <- read_excel("../Data/Table1_raw.xlsx")
Table1_raw
```

::: {style="text-align: center;"}
### Introduction
:::

### Method {style="text-align: center;"}

### Results {style="text-align: center;"}

### Discussion {style="text-align: center;"}

#### References {style="text-align: center;"}

> Andonie, R., and I. Dzitac. 2010. “How to Write a Good Paper in Computer Science and How Will It Be Measured by ISI Web of Knowledge.” International Journal of Computers, Communications & Control V (4): 432–44. https://doi.org/10.15837/ijccc.2010.4.2493.
>
> Frery, A. C., L. Gomez, and A. C. Medeiros. 2020. “A Badging System for Reproducibility and Replicability in Remote Sensing Research.” IEEE Journal of Selected Topics on Applied Earth Observations and Remote Sensing 13: 4988–95. https://doi.org/10.1109/JSTARS.2020.3019 418.
>
> Sánchez del Río, M., Martinetto, P., Solís, C. & Reyes-Valerio, C. (2006), ‘PIXE analysis on Maya blue in Prehispanic and colonial mural paintings’, Nuclear Instruments and Methods in Physics Research Section B: Beam Interactions with Materials and Atoms 249(1–2), 628–632.
